### ISSUE TITLE
TLS cert on ncry.pt has expired, contact email doesn't work

### ISSUE THREAD

**Issue by thefinn93** [luggs-co/ncrypt#1]
The cert on https://ncry.pt has expired. When i went to send an email to the listed contact address (contact@ncry.pt) it does not go through (no MX record and the server that the A/AAAA records points to does not respond on port 25).

**Comment by dansup** [comment]
I have noticed this too, I am working on an [alternative](https://icrypt.ca/) to ncrypt with IPFS, Hyperboria and TOR support. Its [open source](https://github.com/enpaco/php-pastebin), and will use a [spec](https://github.com/enpaco) that will enable decentralized encrypted pastes using IPFS, so one does not have to rely on a single centralized instance.

**Comment by luggs-co** [comment]
I have updated ssl cert, also, have been running TOR version for a while now at ncryptiksb4kubyq.onion
